### ISSUE TITLE
Mind if I fork a python version as a `plotnine` tutorial?

### ISSUE THREAD

**Issue by nickeubank** [rlbarter/ggplot2-thw#1]
Love the tutorial! I'm teaching a datascience course this fall in Python, and would love to use a slightly modified version of your tutorial to teach the python-close of `ggplot` [plotnine](https://plotnine.readthedocs.io/en/stable/index.html). Would you mind if I forked this and put it in my course? I"ll be sure to leave full attribution to you at the top!

**Comment by nickeubank** [comment]
(I saw you said "Feel free to download it and use for your own learning or teaching adventures!", but want to check just to be sure! :))

**Comment by rlbarter** [comment]
Go for it! Please provide proper attribution to my tutorial, but you're welcome to use it as you like :)
